### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by iliuhe** [flytxtds/scene-recognition#1]
Hi, 
I was trying to run your code through anaconda, however I got this error. Any suggestions? Thanks in advance!

He

```
runfile('C:/Users/iliuh/Documents/Python Scripts/scene-recognition-master/scene_recognition_local_global_approach.py', wdir='C:/Users/iliuh/Documents/Python Scripts/scene-recognition-master')
Downloading scene_categories.zip
Traceback (most recent call last):

  File "<ipython-input-3-888f394cc529>", line 1, in <module>
    runfile('C:/Users/iliuh/Documents/Python Scripts/scene-recognition-master/scene_recognition_local_global_approach.py', wdir='C:/Users/iliuh/Documents/Python Scripts/scene-recognition-master')

  File "C:\Users\iliuh\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\iliuh\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/iliuh/Documents/Python Scripts/scene-recognition-master/scene_recognition_local_global_approach.py", line 74, in <module>
    urlretrieve ('http://www-cvr.ai.uiuc.edu/ponce_grp/data/scene_categories/scene_categories.zip', 'scene_categories.zip')

  File "C:\Users\iliuh\Anaconda2\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)

  File "C:\Users\iliuh\Anaconda2\lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)

  File "C:\Users\iliuh\Anaconda2\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)

  File "C:\Users\iliuh\Anaconda2\lib\urllib.py", line 350, in open_http
    h.endheaders(data)

  File "C:\Users\iliuh\Anaconda2\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)

  File "C:\Users\iliuh\Anaconda2\lib\httplib.py", line 882, in _send_output
    self.send(msg)

  File "C:\Users\iliuh\Anaconda2\lib\httplib.py", line 844, in send
    self.connect()

  File "C:\Users\iliuh\Anaconda2\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)

  File "C:\Users\iliuh\Anaconda2\lib\socket.py", line 575, in create_connection
    raise err

IOError: [Errno socket error] [Errno 10061] No connection could be made because the target machine actively refused it
```

**Comment by amarif1** [comment]
Hello @iliuhe,

The notebook uses Fifteen Scene Categories data set by the Ponce Research Group. The URL for the data set is http://www-cvr.ai.uiuc.edu/ponce_grp/data/scene_categories/scene_categories.zip.

The error you have encountered is most probably due to some network connectivity issue. Please make sure that the system is connected to internet. You can also download the data set manually and copy it to the directory containing the notebook.

I hope this resolves the issue.
